#!/bin/bash
# notify.sh - 알림 시스템
# smol.ai 한국어 뉴스 자동 발행 시스템
#
# 크롤러 실패, 검증 실패 등의 이벤트를 알림

_NOTIFY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_NOTIFY_DIR/config.sh"

# 알림 파일 경로
ALERT_FILE="$DATA_DIR/alerts.json"
ALERT_LOG="$LOGS_DIR/alerts.log"

# 알림 레벨
LEVEL_INFO="info"
LEVEL_WARN="warning"
LEVEL_ERROR="error"
LEVEL_CRITICAL="critical"

# 타임스탬프
get_timestamp() {
    date '+%Y-%m-%d %H:%M:%S'
}

# 알림 기록
log_alert() {
    local level="$1"
    local title="$2"
    local message="$3"
    local context="${4:-}"

    local timestamp=$(get_timestamp)

    # 로그 파일에 기록
    mkdir -p "$LOGS_DIR"
    echo "[$timestamp] [$level] $title: $message" >> "$ALERT_LOG"

    # JSON 알림 파일에 추가
    mkdir -p "$DATA_DIR"

    local alert_json=$(cat <<EOF
{
  "timestamp": "$timestamp",
  "level": "$level",
  "title": "$title",
  "message": "$message",
  "context": "$context",
  "acknowledged": false
}
EOF
)

    # alerts.json 업데이트
    if [[ -f "$ALERT_FILE" ]]; then
        # 기존 파일에 추가
        local temp_file=$(mktemp)
        python3 -c "
import json
import sys

alert = json.loads('''$alert_json''')

try:
    with open('$ALERT_FILE', 'r') as f:
        data = json.load(f)
except:
    data = {'alerts': []}

data['alerts'].append(alert)

# 최근 100개만 유지
data['alerts'] = data['alerts'][-100:]

with open('$ALERT_FILE', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
"
    else
        # 새 파일 생성
        echo "{\"alerts\": [$alert_json]}" > "$ALERT_FILE"
    fi

    # 콘솔에도 출력
    case "$level" in
        "$LEVEL_CRITICAL"|"$LEVEL_ERROR")
            echo -e "\033[0;31m[ALERT:$level] $title\033[0m" >&2
            echo "  $message" >&2
            ;;
        "$LEVEL_WARN")
            echo -e "\033[1;33m[ALERT:$level] $title\033[0m" >&2
            echo "  $message" >&2
            ;;
        *)
            echo "[ALERT:$level] $title"
            echo "  $message"
            ;;
    esac
}

# 크롤러 실패 알림
notify_crawler_failure() {
    local url="$1"
    local error="$2"

    log_alert "$LEVEL_CRITICAL" \
        "Crawler Failure" \
        "Failed to crawl: $url. Error: $error" \
        "$url"

    # GitHub Issue 생성
    local issue_body=$(cat <<EOF
## Crawler Failure Alert

**URL:** $url
**Error:** $error
**Time:** $(get_timestamp)

### Description
The news-automation crawler failed to fetch content from smol.ai.
This may indicate a network issue or site unavailability.

### Action Required
1. Check if smol.ai is accessible
2. Review the error message
3. Re-run the pipeline manually if needed

---
*Generated by news-automation*
EOF
)

    create_failure_issue "[Automation] Crawler Failure: $error" "$issue_body" "bug,automation"
}

# 검증 실패 알림 (사이트 구조 변경 감지)
notify_validation_failure() {
    local url="$1"
    local errors="$2"

    log_alert "$LEVEL_ERROR" \
        "Content Validation Failed" \
        "Content validation failed for: $url. Errors: $errors" \
        "$url"

    # GitHub Issue 생성 - 사이트 구조 변경은 중요!
    local issue_body=$(cat <<EOF
## Site Structure Change Detected

**URL:** $url
**Validation Errors:** $errors
**Time:** $(get_timestamp)

### Description
The smol.ai site structure may have changed. The crawler extracted content that failed validation checks.

### Validation Criteria
- Minimum content length: 1000 characters
- Minimum link count: 5 links
- Expected sections: Twitter, Reddit, Discord

### Action Required
1. **Check smol.ai HTML structure** - Look for \`<article class="content-area">\`
2. **Update crawler** if the site structure has changed
3. **Re-run validation** after fixing

### How to Debug
\`\`\`bash
# Check current site structure
curl -s "https://news.smol.ai/issues/..." | grep -o 'class="[^"]*"' | sort -u

# Test crawler
python3 src/crawler/fetch_page.py "$url" --validate-only
\`\`\`

---
*Generated by news-automation*
EOF
)

    create_failure_issue "[Automation] Site Structure Change Detected" "$issue_body" "bug,automation,urgent"
}

# 번역 실패 알림
notify_translation_failure() {
    local slug="$1"
    local error="$2"

    log_alert "$LEVEL_ERROR" \
        "Translation Failed" \
        "Translation failed for: $slug. Error: $error" \
        "$slug"
}

# 리뷰 실패 알림
notify_review_failure() {
    local slug="$1"
    local issues="$2"

    log_alert "$LEVEL_WARN" \
        "Review Failed" \
        "Review failed for: $slug. Issues: $issues" \
        "$slug"
}

# PR 생성 성공 알림
notify_pr_created() {
    local slug="$1"
    local pr_url="$2"

    log_alert "$LEVEL_INFO" \
        "PR Created" \
        "PR created for: $slug. URL: $pr_url" \
        "$pr_url"
}

# GitHub Issue 생성으로 알림 (실패 시)
create_failure_issue() {
    local title="$1"
    local body="$2"
    local labels="${3:-bug,automation}"

    # gh CLI 확인
    if ! command -v gh &> /dev/null; then
        echo "gh CLI not found, skipping issue creation" >&2
        return 1
    fi

    # WEB_REPO_PATH로 이동하여 이슈 생성
    cd "$WEB_REPO_PATH" || return 1

    local issue_url
    issue_url=$(gh issue create \
        --title "$title" \
        --body "$body" \
        --label "$labels" 2>&1) || {
        echo "Failed to create issue: $issue_url" >&2
        return 1
    }

    echo "$issue_url"
}

# 미확인 알림 개수 반환
get_unacknowledged_count() {
    if [[ ! -f "$ALERT_FILE" ]]; then
        echo "0"
        return
    fi

    python3 -c "
import json
try:
    with open('$ALERT_FILE', 'r') as f:
        data = json.load(f)
    count = sum(1 for a in data.get('alerts', []) if not a.get('acknowledged', False))
    print(count)
except:
    print(0)
"
}

# 최근 알림 표시
show_recent_alerts() {
    local count="${1:-5}"

    if [[ ! -f "$ALERT_FILE" ]]; then
        echo "No alerts found."
        return
    fi

    python3 -c "
import json
try:
    with open('$ALERT_FILE', 'r') as f:
        data = json.load(f)
    alerts = data.get('alerts', [])[-$count:]
    for a in reversed(alerts):
        ack = '✓' if a.get('acknowledged') else '○'
        print(f\"{ack} [{a['timestamp']}] [{a['level']}] {a['title']}\")
        print(f\"  {a['message']}\")
except Exception as e:
    print(f'Error: {e}')
"
}

# 직접 실행 시 테스트
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        "test")
            log_alert "$LEVEL_INFO" "Test Alert" "This is a test alert message"
            ;;
        "show")
            show_recent_alerts "${2:-5}"
            ;;
        "count")
            echo "Unacknowledged alerts: $(get_unacknowledged_count)"
            ;;
        *)
            echo "Usage: $0 {test|show [n]|count}"
            ;;
    esac
fi
